# Generated by Django 4.0 on 2022-03-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone number')),
                ('id_no', models.CharField(max_length=50, verbose_name='ID No.')),
                ('deposited_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Deposited Amount')),
                ('date_admitted', models.DateField(verbose_name='Date Admitted')),
                ('is_rented', models.BooleanField(verbose_name='Is Rented')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_renter', to='auth.user', verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='UserAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequrity_question', models.CharField(max_length=50, verbose_name='')),
                ('sequrity_answer', models.CharField(max_length=50, verbose_name='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=10, unique=True, verbose_name='Room No.')),
                ('room_type', models.CharField(max_length=200, verbose_name='Room Type')),
                ('floor_no', models.PositiveIntegerField(verbose_name='Floor No.')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Room Width')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Room Length')),
                ('area', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Area')),
                ('price_msq', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per MSq')),
                ('status', models.CharField(choices=[('occupied', 'OCCUPIED'), ('vacant', 'VACANT'), ('under maintenance', 'UNDER MAINTENANCE'), ('not for rent', 'NOT FOR RENT')], max_length=50, verbose_name='Status')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent.building', verbose_name='Building')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_room', to='auth.user', verbose_name='Created By')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_by_room', to='auth.user', verbose_name='Updated By')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable_month', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Payable Month')),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payable Amount')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total Paid')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.renter', verbose_name='invoice_no')),
            ],
        ),
        migrations.AddField(
            model_name='renter',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='rent.room', verbose_name='Room'),
        ),
        migrations.AddField(
            model_name='renter',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_by_renter', to='auth.user', verbose_name='Updated By'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField(auto_now_add=True, verbose_name='Paid Date')),
                ('no_of_months', models.PositiveIntegerField(verbose_name='No Of Months')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('invoice_no', models.CharField(max_length=50, verbose_name='invoice_no')),
                ('slip_no', models.CharField(max_length=50, verbose_name='Slip_no')),
                ('payment_method', models.CharField(choices=[('cash', 'CASH'), ('bank deposit', 'BANK DEPOSIT'), ('check', 'CHECK')], max_length=50, verbose_name='Payment_method')),
                ('remark', models.CharField(blank=True, default='No Remark.', max_length=50, verbose_name='Remark')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_payment', to='auth.user', verbose_name='Created By')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent.renter', verbose_name='invoice_no')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.report', verbose_name='Reported to.')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_by_payment', to='auth.user', verbose_name='Updated By')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('b_date', models.DateField(verbose_name='Birth Date')),
                ('phone_no', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('sex', models.CharField(max_length=10, verbose_name='Sex')),
                ('role', models.CharField(max_length=20, verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='auth.user', verbose_name='User')),
            ],
        ),
    ]
