# Generated by Django 3.2.9 on 2022-03-14 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradditionalinfo',
            name='sequrity_answer',
        ),
        migrations.RemoveField(
            model_name='useradditionalinfo',
            name='sequrity_question',
        ),
        migrations.AddField(
            model_name='useradditionalinfo',
            name='security_answer',
            field=models.CharField(default='', max_length=50, verbose_name='Sequrity Answer'),
        ),
        migrations.AddField(
            model_name='useradditionalinfo',
            name='security_question',
            field=models.CharField(default='', max_length=50, verbose_name='Sequrity Question'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='report',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='rent.report', verbose_name='Reported to.'),
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
