# Generated by Django 4.0.2 on 2022-03-15 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20220314_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='date_admitted',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Admitted'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='deposited_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Deposited Amount'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='is_rented',
            field=models.BooleanField(default=False, verbose_name='Is Rented'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='rent.room', verbose_name='Room'),
        ),
    ]
