# Generated by Django 4.0.5 on 2022-10-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_remove_renter_id_no_renter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='company_name',
            field=models.CharField(max_length=50, verbose_name='Compane Name'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='phone',
            field=models.IntegerField(max_length=30, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='tin_no',
            field=models.IntegerField(max_length=30, verbose_name='Tin number'),
        ),
    ]
