# Generated by Django 4.0.5 on 2022-10-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_renter_company_name_alter_renter_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='img',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Building Image'),
        ),
        migrations.AddField(
            model_name='renter',
            name='license_img',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Company Licence'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_img',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Room Image'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='chat_id',
            field=models.IntegerField(verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='company_name',
            field=models.CharField(max_length=50, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='phone',
            field=models.IntegerField(verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='tin_no',
            field=models.IntegerField(verbose_name='Tin number'),
        ),
    ]
