# Generated by Django 4.0.2 on 2022-03-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_renter_date_admitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='rent.room', verbose_name='Room'),
        ),
    ]
