# Generated by Django 3.2.9 on 2022-03-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_alter_renter_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent.renter', verbose_name='Renter'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='rent.room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('occupied', 'OCCUPIED'), ('vacant', 'VACANT'), ('under maintenance', 'UNDER MAINTENANCE'), ('not for rent', 'NOT FOR RENT')], default='vacant', max_length=50, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='EmployeeData',
        ),
    ]
