# Generated by Django 3.2.9 on 2022-03-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20220316_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='remark',
            field=models.TextField(blank=True, default='No Remark.', verbose_name='Remark'),
        ),
    ]
