# Generated by Django 3.2.9 on 2022-03-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_auto_20220317_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='rent.roomtype', verbose_name='Room Type'),
        ),
    ]
