# Generated by Django 3.2.9 on 2022-03-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_no',
            field=models.CharField(max_length=50, verbose_name='Invoice No'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'CASH'), ('bank deposit', 'BANK DEPOSIT'), ('check', 'CHECK')], max_length=50, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='slip_no',
            field=models.CharField(max_length=50, verbose_name='Slip No'),
        ),
    ]
