# Generated by Django 4.0.3 on 2022-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0012_alter_renter_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Area'),
        ),
    ]
