# Generated by Django 4.0.3 on 2022-03-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0013_alter_room_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='is_rented',
            field=models.BooleanField(default=True, verbose_name='Is Rented'),
        ),
    ]
