# Generated by Django 4.0.3 on 2022-03-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0014_alter_renter_is_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='date_left',
            field=models.DateField(blank=True, null=True, verbose_name='Date Field'),
        ),
    ]
