# Generated by Django 3.2.9 on 2022-03-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0016_remove_renter_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='chat_id',
            field=models.CharField(default=0, max_length=50, verbose_name='Chat ID'),
        ),
    ]
