# Generated by Django 3.2.9 on 2022-03-31 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0017_renter_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rents', to='rent.room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='report',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.renter', verbose_name='Invoice No.'),
        ),
    ]
