# Generated by Django 3.2.9 on 2022-04-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0018_auto_20220331_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.CharField(max_length=10, verbose_name='Room No.'),
        ),
    ]
