# Generated by Django 3.2 on 2022-05-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0020_penatliy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Penatliy',
            new_name='Penality',
        ),
    ]
