# Generated by Django 3.2.9 on 2022-05-14 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0021_rename_penatliy_penality'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaliyPaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent.report', verbose_name='Penality')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent.renter', verbose_name='Renter')),
            ],
        ),
    ]
