# Generated by Django 4.0.5 on 2022-07-03 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0022_penaliypaymenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_percent', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='Vat Pecentage')),
            ],
        ),
        migrations.DeleteModel(
            name='PenaliyPaymentHistory',
        ),
        migrations.AddField(
            model_name='payment',
            name='vat',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.PROTECT, to='rent.vat', verbose_name='VAT'),
            preserve_default=False,
        ),
    ]
