# Generated by Django 4.0.5 on 2022-07-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0024_alter_payment_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Penality',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='VAT Amount'),
        ),
    ]
