# Generated by Django 4.0.5 on 2022-07-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0025_payment_penality_alter_payment_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Penality',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Penality Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VAT Amount'),
        ),
        migrations.AlterField(
            model_name='penality',
            name='penality_fee_percent',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
