# Generated by Django 4.0.5 on 2022-07-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0026_alter_payment_penality_alter_payment_vat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rent Cost'),
        ),
    ]
