# Generated by Django 4.0.5 on 2022-07-08 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0027_alter_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Penality',
            new_name='penality',
        ),
    ]
