# Generated by Django 4.0.5 on 2022-07-08 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0029_payment_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='total_amount',
        ),
    ]
