# Generated by Django 4.2.4 on 2024-03-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0030_remove_payment_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='deposited_amount',
        ),
    ]
